services:
  lightarr:
    image: aradd7/lightarr:latest
    build: .
    container_name: lightarr
    environment:
      - PORT=${PORT:-10100}
      - X_PLEX_TOKEN=${X_PLEX_TOKEN}
      - WIZ_SUBNET=${WIZ_SUBNET:-192.168.1.0/24}
      - X_PLEX_CLIENT_IDENTIFIER=lightarr-app
      - DB_PATH=/data/lightarr.db
    volumes:
      - ./data:/data
    ports:
      - "${PORT:-10100}:${PORT:-10100}"
    restart: unless-stopped
